### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getSelection' of undefined

### ISSUE THREAD

**Issue by therimalaya** [pimentel/atom-r-exec#2]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: [r-exec](https://github.com/hafen/atom-r-exec) package, v0.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getSelection' of undefined

```
At /Users/therimalaya/.atom/packages/r-exec/lib/r-exec.coffee:45

TypeError: Cannot read property 'getSelection' of undefined
  at Object.module.exports.rstudioserver (/Users/therimalaya/.atom/packages/r-exec/lib/r-exec.coffee:45:49)
  at atom-workspace.<anonymous> (/Users/therimalaya/.atom/packages/r-exec/lib/r-exec.coffee:8:69)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

### Commands

```
     -0:27.6 emmet:expand-abbreviation (input.hidden-input)
     -0:26.3 core:undo (input.hidden-input)
     -0:24.5 grammar-selector:show (atom-text-editor.editor.editor-colors)
  2x -0:21.2 core:backspace (input.hidden-input)
     -0:19.9 core:confirm (input.hidden-input)
     -0:18.7 emmet:expand-abbreviation (input.hidden-input)
     -0:17.8 core:undo (input.hidden-input)
     -0:15.9 emmet:expand-abbreviation (input.hidden-input)
     -0:14.8 core:undo (input.hidden-input)
     -0:00.0 r-exec:send-to-rstudio-server (input.hidden-input)
```

### Config

```
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.17.3
autocomplete-bibtex, v0.4.1
autocomplete-paths, v0.9.1
autocomplete-plus, v1.1.0
autocomplete-snippets, v0.3.2
color-picker, v1.2.6
emmet, v2.3.0
language-knitr, v0.1.0
language-latex, v0.4.1
language-r, v0.1.1
linter, v0.9.0
minimap, v3.4.9
project-manager, v1.14.1
sassbeautify, v0.2.0
wordpress, v0.2.0
wordpress-api, v1.0.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by hafen** [comment]
Interesting. I have the same setup (although not the exact list of other installed packages), and cannot replicate.  Can you provide any more information?  Does this work sometimes but not other times?

**Comment by pimentel** [comment]
@therimalaya is this still an issue in the current version?

**Comment by pimentel** [comment]
Closing issue due to inactivity and I believe the issue is fixed now. Please feel free to reopen the issue if the bug persists.

Thanks
