### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBuffer' of undefined

### ISSUE THREAD

**Issue by wolfemd** [pimentel/atom-r-exec#24]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.4.3
**System**: Mac OS X 10.11.3
**Thrown From**: [r-exec](https://github.com/pimentel/atom-r-exec) package, v0.3.3
### Stack Trace

Uncaught TypeError: Cannot read property 'getBuffer' of undefined

```
At /Users/wolfemd/.atom/packages/r-exec/lib/r-exec.coffee:81

TypeError: Cannot read property 'getBuffer' of undefined
    at Object.module.exports._getEditorAndBuffer (/Users/wolfemd/.atom/packages/r-exec/lib/r-exec.coffee:81:20)
    at Object.module.exports.sendCommand (/Users/wolfemd/.atom/packages/r-exec/lib/r-exec.coffee:86:25)
    at atom-workspace.<anonymous> (/Users/wolfemd/.atom/packages/r-exec/lib/r-exec.coffee:40:34)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -2:22.8.0 r-exec:send-paragraph (atom-text-editor.editor.is-focused)
     -2:19 core:move-left (atom-text-editor.editor.is-focused)
     -2:17.7.0 r-exec:send-paragraph (atom-text-editor.editor.is-focused)
     -2:12.6.0 core:select-down (atom-text-editor.editor.is-focused)
     -2:09.8.0 editor:newline-above (atom-text-editor.editor.is-focused)
     -2:08.9.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:08.3.0 editor:newline-below (atom-text-editor.editor.is-focused)
     -2:07.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:06.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:06.3.0 editor:newline-below (atom-text-editor.editor.is-focused)
     -2:04.5.0 core:undo (atom-text-editor.editor.is-focused)
     -2:03.6.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:03.2.0 core:select-down (atom-text-editor.editor.is-focused)
     -2:02.7.0 editor:newline-below (atom-text-editor.editor.is-focused)
  2x -1:59.3.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -0:16.9.0 r-exec:send-command (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {},
  "r-exec": {
    "whichApp": "Terminal"
  }
}
```
### Installed Packages

``` coffee
# User
language-r, v0.4.0
minimap, v4.19.0
r-exec, v0.3.3

# Dev
No dev packages
```

**Comment by pimentel** [comment]
@wolfemd could you provide some background on how to reproduce this bug? under what conditions did this happen? thanks!

**Comment by koenvandenberge** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.4
**Thrown From**: [r-exec](https://github.com/pimentel/atom-r-exec) package, v0.3.5


### Stack Trace

Uncaught TypeError: Cannot read property 'getBuffer' of undefined

```
At /Users/koenvandenberge/.atom/packages/r-exec/lib/r-exec.coffee:87

TypeError: Cannot read property 'getBuffer' of undefined
    at Object.module.exports._getEditorAndBuffer (/Users/koenvandenberge/.atom/packages/r-exec/lib/r-exec.coffee:87:20)
    at Object.module.exports.sendCommand (/Users/koenvandenberge/.atom/packages/r-exec/lib/r-exec.coffee:92:25)
    at atom-workspace.<anonymous> (/Users/koenvandenberge/.atom/packages/r-exec/lib/r-exec.coffee:42:34)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
 10x -2:37.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:34.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -2:34.2.0 core:cancel (atom-text-editor.editor.is-focused)
     -2:26.2.0 application:add-project-folder (atom-text-editor.editor.mini.is-focused)
     -2:15.9.0 editor:newline-below (atom-text-editor.editor.is-focused)
     -2:12.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:11.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:59.2.0 key-binding-resolver:toggle (div.panels)
 14x -1:50.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:46.1.0 r-exec:send-command (atom-text-editor.editor.mini.is-focused)
     -0:38.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:36.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:32 r-exec:send-command (atom-text-editor.editor.mini.is-focused)
  3x -0:08.7.0 core:undo (atom-text-editor.editor.is-focused)
     -0:05.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:00.0 r-exec:send-command (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-gfm",
      "atom-runner"
    ]
  },
  "r-exec": {
    "whichApp": "Terminal"
  }
}
```

### Installed Packages

```coffee
# User
atom-runner, v2.7.1 (inactive)
language-markdown, v0.16.3 (active)
language-r, v0.4.1 (active)
r-exec, v0.3.5 (active)
script, v3.9.0 (inactive)
terminal-plus, v0.14.5 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by pimentel** [comment]
did you folks just update atom?

**Comment by koenvandenberge** [comment]
Yes, I downloaded the latest version.

**Comment by pimentel** [comment]
Thanks, @koenvandenberge. I will update later today and take a look. At a first glance, it looks like it is probably a simple fix.

**Comment by pimentel** [comment]
@koenvandenberge I'm having trouble reproducing this on the latest Atom. did you have anything in the buffer when you tried to activate the package?
