### ISSUE TITLE
Uncaught Error: write EPIPE

### ISSUE THREAD

**Issue by WangJS33314** [pimentel/atom-r-exec#34]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Unknown Windows Version
**Thrown From**: [r-exec](https://github.com/pimentel/atom-r-exec) package, v0.3.4

### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:141

Error: write EPIPE
    at exports._errnoException (util.js:856:11)
    at Socket._writeGeneric (net.js:675:26)
    at Socket._write (net.js:694:8)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Socket.Writable.write (_stream_writable.js:207:11)
    at Socket.write (net.js:618:40)
    at execute (C:\Users\wjsbean\.atom\packages\r-exec\node_modules\node-osascript\lib\index.js:56:12)
    at Object.module.exports.execute (C:\Users\wjsbean\.atom\packages\r-exec\node_modules\node-osascript\lib\index.js:64:5)
    at Object.module.exports.terminal (file:///C:/Users/wjsbean/.atom/packages/r-exec/lib/r-exec.coffee:450:15)
    at Object.module.exports.sendCode (file:///C:/Users/wjsbean/.atom/packages/r-exec/lib/r-exec.coffee:109:32)
    at Object.module.exports.sendCommand (file:///C:/Users/wjsbean/.atom/packages/r-exec/lib/r-exec.coffee:91:6)
    at atom-workspace.<anonymous> (file:///C:/Users/wjsbean/.atom/packages/r-exec/lib/r-exec.coffee:40:34)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\wjsbean\AppData\Local\atom\app-1.7.3\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\wjsbean\AppData\Local\atom\app-1.7.3\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\wjsbean\AppData\Local\atom\app-1.7.3\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\wjsbean\AppData\Local\atom\app-1.7.3\resources\app.asar\src\atom-environment.js:1100:28)
    at EventEmitter.outerCallback (C:\Users\wjsbean\AppData\Local\atom\app-1.7.3\resources\app.asar\src\application-delegate.js:314:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -1:03.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:49.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:12.9.0 r-exec:send-knitr (atom-text-editor.editor.is-focused)
     -0:07.1.0 r-exec:send-command (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-gfm"
    ]
  },
  "r-exec": {
    "whichApp": "Terminal"
  }
}
```

### Installed Packages

```coffee
# User
atom-python-test, v0.1.7
autocomplete-python, v1.7.2
language-markdown, v0.13.0
language-r, v0.4.1
linter, v1.11.4
linter-lintr, v1.0.4
linter-python-pep8, v0.2.0
minimap, v4.23.5
python-autopep8, v0.1.3
python-debugger, v0.1.0
python-indent, v0.4.3
python-jedi, v0.3.6
r-exec, v0.3.4

# Dev
No dev packages
```

**Comment by pimentel** [comment]
Currently unsupported on Windows and I don't have a machine to develop on/or the time to get this to work.

If you are interested in spearheading this, I am more than happy to help.
