### ISSUE TITLE
Failed to load the r-exec package

### ISSUE THREAD

**Issue by ashwingrao** [pimentel/atom-r-exec#4]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.2
**Thrown From**: [r-exec](https://github.com/hafen/atom-r-exec) package, v0.1.0

### Stack Trace

Failed to load the r-exec package

```
At Cannot read property 'getPath' of null

TypeError: Cannot read property 'getPath' of null
  at Object.<anonymous> (/Users/indu/.atom/packages/r-exec/lib/r-exec.coffee:58:13)
  at Object.<anonymous> (/Users/indu/.atom/packages/r-exec/lib/r-exec.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:665:34)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:174:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:152:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:166:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:355:14)
  at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:325:14)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app/src/atom.js:631:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:54:25)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "vim-mode"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.4.4
linter, v0.11.1
merge-conflicts, v1.2.10
r-exec, v0.1.0
run-command, v0.1.1

# Dev
No dev packages
```

**Comment by pimentel** [comment]
I'm willing to bet this is fixed in the latest version and I am closing the issue for now. If it is not fixed, please feel free to update and reopen this issue.

Thanks.
